apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: udplistener-vhf
  name: udplistener-vhf
  namespace: udplistener
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: udplistener-vhf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: udplistener-vhf
    spec:
      containers:
      - args:
        - /udplistener
        - -port
        - "23457"
        - -host
        - radio-cluster-kafka-bootstrap.strimzi-operator
        image: lude/udplistener:latest
        imagePullPolicy: Always
        name: udplistener
        ports:
        - containerPort: 23457
          name: audioudp
          protocol: UDP
      nodeSelector:
        kubernetes.io/hostname: blizzard
      restartPolicy: Always
