apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: udplistener-dtrs
  name: udplistener-dtrs
  namespace: udplistener
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: udplistener-dtrs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: udplistener-dtrs
    spec:
      containers:
      - args:
        - /udplistener
        - -port
        - "23456"
        - -host
        - "amqp://user:agnQzKKlDYP33vQA@rabbitmq-rabbitmq.rabbitmq:5672/"
        - -queue
        - audio-buffer-dtrs
        image: lude/udplistener:latest
        imagePullPolicy: Always
        name: udplistener
        ports:
        - containerPort: 23456
          name: audioudp
          protocol: UDP
      nodeSelector:
        kubernetes.io/hostname: blizzard
      restartPolicy: Always
