apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: udplistener-dtrs
  name: udplistener-dtrs
  namespace: udplistener
spec:
  ports:
  - name: udpradio
    port: 23456
    protocol: UDP
    targetPort: 23456
  selector:
    app.kubernetes.io/name: udplistener-dtrs
  type: ClusterIP
