apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: udplistener-vhf
  name: udplistener-vhf
  namespace: udplistener
spec:
  ports:
  - name: udpradio
    port: 23457
    protocol: UDP
    targetPort: 23457
  selector:
    app.kubernetes.io/name: udplistener-vhf
  type: ClusterIP
