---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: flux-system
spec:
  chart:
    spec:
      chart: woodpecker
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: woodpecker
  targetNamespace: woodpecker
  install:
    createNamespace: true
  interval: 1m0s
  values:
    persistentVolume:
      storageClass: local-storage
    nodeSelector:
      kubernetes.io/hostname: avalanche
