apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: zigbee2mqtt-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /storage/kubernetes/zigbee2mqtt/data
    type: ''
  claimRef:
    namespace: zigbee2mqtt
    name: data-volume-zigbee2mqtt-zigbee2mqtt-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
