---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gitea
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitea
  targetNamespace: gitea
  install:
    createNamespace: true
  interval: 10m
  values:
    nodeSelector:
      kubernetes.io/hostname: avalanche
    persistence:
      enabled: true
      storageClass: local-storage
      volumeName: gitea-shared-storage
    gitea:
      config:
        database:
          DB_TYPE: postgres
          HOST: postgresql-postgresql.postgresql
          NAME: gitea
          USER: gitea_user
          PASSWD: WLUJdw3fNhGS
          SCHEMA: gitea
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    redis-cluster:
      enabled: false
    redis:
      enabled: true
    ingress:
      enabled: true
      className: traefik-traefik
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      hosts:
      - host: gitea.lude.net
        paths:
        - path: /
          pathType: Prefix
    service:
      ssh:
        type: ClusterIP
        port: 22
        externalIPs:
        - 172.16.10.8
