---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gitea
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitea
  targetNamespace: gitea
  install:
    createNamespace: true
  interval: 1m0s
  values:
    nodeSelector:
      kubernetes.io/hostname: avalanche
    persistence:
      enabled: true
      storageClass: local-storage
    redis-cluster:
      enabled: false
    redis:
      enabled: true
    gitea:
      config:
        database:
          DB_TYPE: postgresql
          HOST: postgresql-postgresql.postgresql
          NAME: gitea
          USER: gitea_user
          PASSWD: WLUJdw3fNhGS
          SCHEMA: gitea
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
