apiVersion: v1
kind: PersistentVolume
metadata:
  name: valkey-data-gitea-gitea-valkey-cluster-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /storage/kubernetes/gitea/valkey-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - avalanche
