apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-data
  namespace: homebridge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: homebridge-data
