---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homebridge
  namespace: flux-system
spec:
  chart:
    spec:
      chart: homebridge
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  targetNamespace: homebridge
  install:
    createNamespace: true
  interval: 1m0s
  values:
    logging:
      promtail:
        enabled: true
        image:
          pullPolicy: IfNotPresent
          repository: grafana/promtail
          tag: 2.1.0
        loki:
          url: http://loki.grafana:3100/loki/api/v1/push
    nodeSelector:
      kubernetes.io/hostname: blizzard
    hostNetwork: true
    service:
      main:
        externalIPs:
        - 172.16.10.10
        ports:
          http:
            port: 8581
            protocol: TCP
    persistence:
      config:
        accessMode: ReadWriteOnce
        claimName: homebridge-data
        enabled: true
        existingClaim: homebridge-data
        size: 50Gi
        mountPath: /homebridge

    config: |
      #!/bin/sh
      #
      npm install homebridge-broadlink-rm homebridge-mqttthing zigbeemqtt 
      # apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev
