apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmq-rabbitmq-0
  namespace: rabbitmq
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: data-rabbitmq-rabbitmq-0
