---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rabbitmq
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  targetNamespace: rabbitmq
  install:
    createNamespace: true
  interval: 1m0s
  values:
    global:
      defaultStorageClass: local-storage
    nodeSelector:
      kubernetes.io/hostname: avalanche
    persistence:
      data:
        accessMode: ReadWriteOnce
        claimName: rabbitmq-data
        enabled: true
        existingClaim: rabbitmq-data
        size: 50Gi
