---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ping-exporter
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/czerwonk/ping_exporter
  ref:
    branch: main
