---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ping-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ping-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ping-exporter
  targetNamespace: prometheus
  install:
    createNamespace: true
  interval: 10m
