---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ping-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ping-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ping-exporter
  targetNamespace: prometheus
  install:
    createNamespace: true
  interval: 10m
  values:
    config:
    targets:
      - 8.8.8.8
      - 8.8.4.4
      - 73.229.38.1
      - google.com

    dns:
      refresh: 2m15s
      nameserver: 172.16.10.4

    ping:
      interval: 2s
      timeout: 3s
      history-size: 42
      payload-size: 120

    serviceMonitor:
      enabled: true
