---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
  targetNamespace: prometheus
  install:
    createNamespace: true
  interval: 10m
  values:
    nodeSelector:
      kubernetes.io/hostname: blizzard
    persistence:
      enabled: true
      storageClass: local-storage
