---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
  targetNamespace: minio
  install:
    createNamespace: true
  interval: 10m
  values:
    tenant:
      name: storage
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 10Gi
          nodeSelector:
            kubernetes.io/hostname: avalanche
      # Configures a Prometheus-compatible scraping endpoint at the specified port.
      metrics:
        enabled: true
        port: 9000
        protocol: http
      prometheusOperator: true
    ingress:
      api:
        enabled: true
        ingressClassName: traefik-traefik
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        host: minio.lude.net
        path: /
        pathType: Prefix
      console:
        enabled: true
        ingressClassName: traefik-traefik
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        host: minio-console.lude.net
        path: /
        pathType: Prefix
