---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: minio-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
  targetNamespace: minio
  install:
    createNamespace: true
  interval: 10m
