---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
      interval: 5m
  releaseName: minio
  targetNamespace: minio
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    nodeSelector:
      kubernetes.io/hostname: avalanche
    persistence:
      storageClass: local-storage
      size: 10Gi
