---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/minio
