---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: flux-system
spec:
  chart:
    spec:
      chart: actualbudget
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actualbudget
  targetNamespace: actualbudget
  install:
    createNamespace: true
  interval: 10m
  values:
    strategy:
      type: Recreate

    files:
      server: /data/server-files
      user: /data/user-files

    ingress:
      enabled: true
      hosts:
        - host: budget.lude.net
          paths:
            - path: /
              pathType: ImplementationSpecific

    persistence:
      enabled: true
      existingClaim: actualbudget-volume
