---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mosquitto
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  targetNamespace: mosquitto
  install:
    createNamespace: true
  interval: 1m0s
  values:
    logging:
      promtail:
        enabled: true
        image:
          pullPolicy: IfNotPresent
          repository: grafana/promtail
          tag: 2.1.0
        loki:
          url: http://loki.grafana:3100/loki/api/v1/push
    nodeSelector:
      kubernetes.io/hostname: blizzard
    service:
      main:
        externalIPs:
        - 172.16.10.10
        ports:
          http:
            port: 1883
            protocol: TCP
