---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: flux-system
spec:
  chart:
    spec:
      chart: drone
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: drone
  targetNamespace: drone
  install:
    createNamespace: true
  interval: 1m0s
  values:
    env:
      DRONE_SERVER_HOST: "drone.lude.net"
      DRONE_GITEA_CLIENT_ID: "c30e03e0-b703-42ba-8763-648ed0e4664d"
      DRONE_GITEA_CLIENT_SECRET: "redacted"
      DRONE_GITEA_SERVER: "http://gitea-gitea-http.gitea:3000/"
    persistentVolume:
      storageClass: local-storage
    nodeSelector:
      kubernetes.io/hostname: avalanche
