apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-watch
  namespace: transmission
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: transmission-watch
