apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: scrypted-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /storage/kubernetes/scrypted/scrypted-server
    type: DirectoryOrCreate
  claimRef:
    namespace: scrypted
    name: scrypted-server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
