---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrypted
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: scrypted
      sourceRef:
        kind: HelmRepository
        name: truecharts
      interval: 5m
  releaseName: scrypted
  targetNamespace: scrypted
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
