---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrypted
  namespace: default
spec:
  interval: 10m
  releaseName: scrypted
  chartRef:
    kind: OCIRepository
    name: truecharts
  targetNamespace: scrypted
  install:
    createNamespace: true

