apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: scrypted-media
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /storage/kubernetes/scrypted/scrypted-media
    type: DirectoryOrCreate
  claimRef:
    namespace: scrypted
    name: scrypted-media
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
