---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  chart:
    spec:
      chart: plex
      reconcileStrategy: ChartVersion
    install:
      targetNamespace: plex
      createNamespace: true
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 1m0s
  values:
    affinity: {}
    certificate:
      pkcsMangler:
        certificateSecret:
          crtName: tls.crt
          keyName: tls.key
          name: ""
          volume:
            mountPath: /etc/plex-certs
            name: plex-certs
        configmap:
          annotations: {}
          labels: {}
          name: 42-pkcs-mangler
        enabled: false
        image:
          repository: tlsprint/openssl
          tag: 1.1.1f
        pfxInContainerPath: /config/plex.pfx
        pfxPassword:
          annotations: {}
          labels: {}
          passwordKey: pfx-password
          secretName: plex-media-server-pfx-password
          value: setpassword
        setPlexPreferences:
          customCertificateDomain: ""
          enabled: true
        volume:
          defaultMode: 493
          mountPath: /etc/cont-init.d/42-pkcs-mangler
          name: 42-pkcs-mangler
          subPath: 42-pkcs-mangler
    claimToken: ""
    deploymentAnnotations: {}
    fullnameOverride: ""
    hostNetwork: false
    image:
      pullPolicy: IfNotPresent
      repository: plexinc/pms-docker
      tag: 1.31.1.6733-bc0674160
    imagePullSecrets: []
    ingress:
      main:
        enabled: false
    logging:
      promtail:
        enabled: true
        image:
          pullPolicy: IfNotPresent
          repository: grafana/promtail
          tag: lastest
        loki:
          url: http://loki.grafana:3100/loki/api/v1/push
    nodeSelector:
      kubernetes.io/hostname: avalanche
    persistence:
      config:
        accessMode: ReadWriteOnce
        claimName: plex-config
        enabled: true
        existingClaim: plex-config
        size: 50Gi
      data:
        accessMode: ReadWriteOnce
        claimName: plex-data
        enabled: true
        existingClaim: plex-data
        size: 50Gi
      transcode:
        accessMode: ReadWriteOnce
        claimName: plex-transcode
        enabled: true
        existingClaim: plex-transcode
        size: 50Gi
    plexPreferences:
      configmap:
        annotations: {}
        labels: {}
        name: 41-plex-preferences
      enabled: false
      volume:
        defaultMode: 493
        mountPath: /etc/cont-init.d/41-plex-preferences
        name: 41-plex-preferences
        subPath: 41-plex-preferences
    podAnnotations: {}
    podSecurityContext: {}
    probes:
      liveness:
        enabled: true
        failureThreshold: 5
        httpGet:
          path: /identity
          port: 32400
        periodSeconds: 10
      readiness:
        enabled: true
        failureThreshold: 5
        httpGet:
          path: /identity
          port: 32400
        periodSeconds: 10
      startup:
        enabled: true
        failureThreshold: 30
        httpGet:
          path: /identity
          port: 32400
        initialDelaySeconds: 5
        periodSeconds: 10
    proxy:
      enabled: false
    resources: {}
    securityContext: {}
    service:
      main:
        ports:
          http:
            enabled: true
            nodePort: 32400
            port: 32400
        primary: true
        type: NodePort
    strategyType: Recreate
    timezone: UTC
    tolerations: []

