apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-jellyfin-config
  labels:
    jellyfin-volume: config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  hostPath:
    path: /storage/kubernetes/jellyfin/jellyfin/config
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
