apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-jellyfin-media
  labels:
    jellyfin-volume: media
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /storage/kubernetes/jellyfin/jellyfin/media
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
