---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jellyfin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jellyfin
  targetNamespace: jellyfin
  install:
    createNamespace: true
  interval: 10m
  values:
    nodeSelector:
      kubernetes.io/hostname: avalanche
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 25Gi
        storageClass: 'local-storage'
      media:
        enabled: true
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: 'local-storage'

