---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jellyfin/jellyfin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jellyfin
  targetNamespace: jellyfin
  install:
    createNamespace: true
  interval: 10m
  values:
    nodeSelector:
      kubernetes.io/hostname: avalanche
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 5Gi
        annotations: {}
        storageClass: 'local-storage'
      media:
        # -- set to false to use emptyDir
        enabled: true
        type: hostPath
        hostPath: "/storage/kubernetes/plex/plex/data"
        accessMode: ReadWriteOnce
        size: 25Gi

