---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-operator
  namespace: flux-system
spec:
  chart:
    git: https://github.com/strimzi/strimzi-kafka-operator
    path: helm-charts/helm3/strimzi-kafka-operator
    ref: 0.43.0
  targetNamespace: strimzi-operator
  install:
    createNamespace: true
  interval: 1m0s
