---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: strimzi/strimzi-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: strimzi-operator
  targetNamespace: strimzi-operator
  install:
    createNamespace: true
  interval: 1m0s
