apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtlsdr
  namespace: rtlsdr
  labels:
    app.kubernetes.io/name: rtlsdr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rtlsdr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rtlsdr
    spec:
      containers:
      - image: lude/rtlsdr-airband:latest
        imagePullPolicy: Always
        name: rtlsdr
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /usr/local/etc/rtl_airband.conf
          name: rtlsdr-config
          subPath: rtl_airband.conf
        - mountPath: /dev
          name: dev
        - mountPath: /sys
          name: sys
      nodeSelector:
        kubernetes.io/hostname: swell
      volumes:
      - name: rtlsdr-config
        configMap:
          name: rtlsdr
          defaultMode: 0644
      - name: sys
        hostPath:
          path: /sys
      - name: dev
        hostPath:
          path: /dev
