---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: buildkit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: buildkit-service
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: andrcuns
  targetNamespace: buildkit
  install:
    createNamespace: true
  interval: 10m
  values:
    nodeSelector:
      kubernetes.io/hostname: avalanche

