---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: flux-system
spec:
  chart:
    spec:
      chart: unifi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  targetNamespace: unifi
  install:
    createNamespace: true
  interval: 1m0s
  values:
    GID: 999
    UID: 999
    customCert:
      enabled: false
    extraJvmOpts: []
    image:
      pullPolicy: IfNotPresent
      repository: jacobalberty/unifi
      tag: v7.3.83
    jvmInitHeapSize: null
    jvmMaxHeapSize: 1024M
    livenessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    logging:
      promtail:
        enabled: true
        image:
          pullPolicy: IfNotPresent
          repository: grafana/promtail
          tag: 2.1.0
        loki:
          url: http://loki.grafana:3100/loki/api/v1/push
    mongodb:
      enabled: false
    nodeSelector:
      kubernetes.io/hostname: lightning
    persistence:
      data:
        accessMode: ReadWriteOnce
        claimName: unifi-data
        enabled: true
        existingClaim: unifi-data
        size: 50Gi
    readinessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    runAsRoot: false
    service:
      main:
        externalIPs:
        - 172.16.10.10
        ports:
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
          http:
            port: 8443
            protocol: HTTPS
          portal-http:
            enabled: false
            port: 8880
            protocol: HTTP
          portal-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          speedtest:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
