---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: caddy
  namespace: flux-system
spec:
  chart:
    spec:
      chart: caddy-ingress-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: caddy
  targetNamespace: caddy-system
  install:
    createNamespace: true
  interval: 10m
