apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: kafka-zookeeper-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /storage/kubernetes/strimzi/data-kafka-zookeeper-0
    type: DirectoryOrCreate
  claimRef:
    namespace: strimzi
    name: data-kafka-zookeeper-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
