apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: flux-system
spec:
  chart:
    spec:
      chart: strimzi-kafka-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: strimzi
  targetNamespace: strimzi
  install:
    createNamespace: true
  interval: 1m0s
