apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi
  namespace: flux-system
spec:
  chart:
    spec:
      chart: strimzi-kafka-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: strimzi
  targetNamespace: strimzi
  install:
    createNamespace: true
  interval: 10m
  values:
    resources:
      limits:
        memory: 1024Mi
        cpu: 1000m
      requests:
        memory: 512Mi
        cpu: 400m
