---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ping-exporter
  namespace: flux-system
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/czerwonk/ping_exporter/main/dist/charts/
